### ISSUE TITLE
点播httpflv后程序报panic

### ISSUE THREAD

**Issue by comeonbabydontbeshy** [Monibuca/plugin-hdl#2]
panic内容如下：
```log
2022/07/13 17:25:48 http: panic serving 127.0.0.1:53248: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1()
	/home/SENSETIME/linjian1/sdk/go1.18/src/net/http/server.go:1825 +0xbf
panic({0x83cae0, 0xc02700})
	/home/SENSETIME/linjian1/sdk/go1.18/src/runtime/panic.go:844 +0x258
net/http.(*ServeMux).redirectToPathSlash(0x0, {0xc0003a0231?, 0x40?}, {0xc0000c4064, 0x12}, 0xc000182000)
	/home/SENSETIME/linjian1/sdk/go1.18/src/net/http/server.go:2347 +0x53
net/http.(*ServeMux).Handler(0x7f8760a41c58?, 0xc000166f00)
	/home/SENSETIME/linjian1/sdk/go1.18/src/net/http/server.go:2419 +0x1c5
net/http.(*ServeMux).ServeHTTP(0x0?, {0x95dfa0, 0xc0000c20e0}, 0xc000166f00)
	/home/SENSETIME/linjian1/sdk/go1.18/src/net/http/server.go:2461 +0x12e
net/http.serverHandler.ServeHTTP({0xc0000baea0?}, {0x95dfa0, 0xc0000c20e0}, 0xc000166f00)
	/home/SENSETIME/linjian1/sdk/go1.18/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0003994a0, {0x95e458, 0xc000292180})
	/home/SENSETIME/linjian1/sdk/go1.18/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/home/SENSETIME/linjian1/sdk/go1.18/src/net/http/server.go:3071 +0x4db
```

测试代码如下：
```go
package main

import (
	"context"

	"m7s.live/engine/v4"

	_ "m7s.live/plugin/hdl/v4"
	_ "m7s.live/plugin/rtmp/v4"
)

func main() {
	engine.Run(context.Background(), "./config.yaml")
}
```

配置如下
```config
global: #全局配置
    publish: # 发布者配置（可被插件中相同的配置项覆盖）
        pubaudio: true # 是否发布音频
        pubvideo: true # 是否发布视频
        kickexist: false # 是否提出已经存在的发布者
        publishtimeout: 10 # 发布者无数据10秒后自动发布失败
        waitclosetimeout: 0 # 当无人订阅时N秒后自动关闭流，0代表不关闭
    subscribe: # 订阅者配置（可被插件中相同的配置项覆盖）
        subaudio: true # 是否订阅音频
        subvideo: true # 是否订阅视频
        iframeonly: false # 是否只订阅关键帧
        waittimeout: 10 # 订阅后N秒后仍然无发布者，则订阅失败
    http: # web server配置项（可被插件中相同的配置项覆盖）
        listenaddr: :8085 # 默认开启的http端口
        listenaddrtls: "" # https端口
        certfile: "" # https用到的证书
        keyfile: "" # https用到的证书的key
        cors: true # 开启自动添加CORS头
        username: "" # 基本身份认证的用户名
        password: "" # 基本身份认证的密码
    rtpreorder: false # 是否开启rtp包乱序重排功能
    enableavcc: true # 是否开启avcc格式缓存
    enablertp: true # 是否开启rtp包格式缓存
    enableflv: true # 是否开启flv格式缓存
    consoleurl: wss://console.monibuca.com:8080 # 远程管理界面地址
    secret: "" # 远程管理的密钥

rtmp:
    publish:
        pubaudio: true
        pubvideo: true
        kickexist: false
        publishtimeout: 10
        waitclosetimeout: 0
    subscribe:
        subaudio: true
        subvideo: true
        iframeonly: false
        waittimeout: 10
    tcp:
        listenaddr: :1936
        listennum: 0
    pull:
        repull: 0 # 当断开后是否自动重新拉流，0代表不进行重新拉流，-1代表无限次重新拉流
        pullonstart: false # 是否在m7s启动的时候自动拉流
        pullonsubscribe: false  # 是否在有人订阅的时候自动拉流（按需拉流）
        pulllist: {} # 拉流列表，以 streamPath为key，远程地址为value
    push:
        repush: 0 # 当断开后是否自动重新推流，0代表不进行重新推流，-1代表无限次重新推流
        pushlist: {} # 推流列表，以 streamPath为key，远程地址为value
    chunksize: 4096
    keepalive: false #保持rtmp连接，默认随着stream的close而主动断开

hdl:
    http:
        listenaddr: :8011
        listenaddrtls: ""
        certfile: ""
        keyfile: ""
        cors: true
        username: ""
        password: ""
    publish:
        pubaudio: true
        pubvideo: true
        kickexist: false
        publishtimeout: 10
        waitclosetimeout: 0
    subscribe:
        subaudio: true
        subvideo: true
        iframeonly: false
        waittimeout: 10
    pull:
        repull: 0
        pullonstart: false
        pullonsubscribe: false
        pulllist: {}
```

**Comment by langhuihui** [comment]
你做了什么操作呢？

**Comment by comeonbabydontbeshy** [comment]
1.推送rtmp流至monibuca，rtmp流可以正常点播
``` shell
ffmpeg -re -stream_loop -1 -i ./big_buck_bunny_720p_1mb.flv -c copy -f flv rtmp://localhost:1936/live/test
```
2.点播http-flv流，点播失败，看日志打印panic
```shell
http://localhost:8011/hdl/live/test.flv
```
